version: 2
jobs:
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: Deploy Master to Heroku
      command: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
        filters:
          branches:
            only: develop
